const fs = require('fs');
const newData = [
  {
    "root": "أنّ",
    "root_meaning_html": "<p>According to Ibn Faris in <em>Maqayis al-Lughah</em>, the doubled hamza and nun (أَنّ) finds its foundational physical origin in a sound of lamentation and sighing (<em>al-sawt bi-tawujju’</em>). Al-Khalil observes that a person is said to groan (<em>anna al-rajulu ya’innu aninan</em>) when expressing deep internal pain or grief. The linguistic nuance extends to the bending and softening of a bow's tone as it stretches. Thus, the root inherently captures a strained, resonant outflow of breath mirroring human yearning, complaint, or modal emphasis.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops particles of certainty, subordination, and explanatory force that bind clauses together with emotional and logical resonance. It manifests as the accusative particle of emphasis (أَنَّ), structural subordination, and explanatory nuance, operating like a psychological sigh of realization. A profound Quranic instance occurs in the divine decree: <em>Wa-an tasumu khayrun lakum</em> (And that you fast is better for you), where the particle bridges human action with transcendent moral weight.</p>" 
  },
  {
    "root": "أهل",
    "root_meaning_html": "<p>As explained by Al-Raghib al-Isfahani in <em>Al-Mufradat</em>, the primary physical picture of <em>ahl</em> (أَهْل) denotes those who share a single dwelling or resting place. Over time, the term broadened metaphorically to encompass those united by lineage, religious creed, craft, or homeland. A place is termed <em>ma'hul</em> when it is inhabited by its people, while the verb <em>ta'ahkala</em> signifies entering into marriage. The linguistic nuance highlights deep intimacy, belonging, and fitness; thus, declaring someone <em>ahl</em> for a task means they are thoroughly qualified and suited for it.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops profound relational paradigms defining spiritual kinship, household sanctity, and moral exclusion. It distinguishes biological ties from ideological alignment, as seen in the address concerning Noah's family: <em>Innahu laysa min ahlika innahu amalun ghayru salih</em> (Indeed, he is not of your family; indeed, he is [one of] righteous work). Similarly, it elevates the status of divine intimacy in the supreme honor of <em>Ahl al-Bayt</em>.</p>"
  },
  {
    "root": "أو",
    "root_meaning_html": "<p>Lexicographers such as Al-Fayruzabadi in <em>Al-Qamus al-Muhit</em> define <em>aw</em> (أَوْ) as a versatile particle governing disjunction, hesitation, and alternatives. Its foundational linguistic function is to present multiple trajectories without definitive closure, capturing the mental state of choosing, dividing, or approximating. Whether expressing ambiguity (<em>al-ibham</em>), choice (<em>al-takhyir</em>), or serving as a substitution for <em>bal</em> (rectification), the root maps the fluid boundaries of human perception when facing distinct conceptual paths.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops delicate nuances of theological dialogue, ethical options, and rhetorical transitions. It gracefully structures human realities between certainty and approximation, or divine commands offering lawful breadth. A striking Quranic example appears in the divine declaration: <em>Wa-inna aw iyyakum la-ala hudan aw fi dalalin mubin</em> (And indeed, we or you are either upon guidance or in clear error), masterfully balancing polemical restraint with profound open-ended truth.</p>"       
  },
  {
    "root": "أوب",
    "root_meaning_html": "<p>Al-Raghib al-Isfahani notes in <em>Al-Mufradat</em> that <em>al-awb</em> (اَلْأَوْب) signifies a specific type of return: one executed by a sentient being endowed with will and conscious intent. While general return (<em>ruju'</em>) applies to anything, <em>awb</em> implies a deliberate turning back toward an origin or home. The intensive form <em>awwab</em> describes the one who repeatedly and enthusiastically turns back to God by abandoning sin and embracing righteousness. The linguistic nuance emphasizes a willful, heartfelt homecoming of the soul.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops exalted descriptions of spiritual repentance, cosmic return, and obedient harmony. It captures the ultimate trajectory of human destiny toward the divine presence and the harmonious reverberation of creation. A magnificent Quranic illustration is found in the command to the mountains: <em>Ya jibalu awwibi ma'ahu</em> (O mountains, repeat [Praise] with him), where nature joins the prophet in an eternal, rhythmic returning to God.</p>"
  },
  {
    "root": "أود",
    "root_meaning_html": "<p>According to Ibn Manzur in <em>Lisan al-Arab</em>, the root <em>awd</em> (أَوْد) portrays the physical reality of severe burden, crushing weight, and structural crookedness. To say <em>adahu al-amr</em> means an affair reached the utmost limit of exhausting strain upon him. Conversely, <em>al-awad</em> denotes physical curvature or warping, while <em>al-thiqaf</em> is the instrument used to straighten what has bent. The linguistic nuance intricately balances the concepts of oppressive heaviness that causes bending with the resilient effort required to uphold and straighten a load.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops majestic expressions of absolute divine transcendence, omnipotence, and effortless preservation. It highlights the staggering contrast between human frailty under heavy burdens and the infinite capacity of the Creator. An immortal Quranic example is enshrined in the Throne Verse: <em>Wa la yauduhu hifzuhuma</em> (And the preservation of them [the heavens and earth] does not tire Him), affirming that sustaining creation causes Him no strain whatsoever.</p>"
  },
  {
    "root": "أول",
    "root_meaning_html": "<p>Ibn Manzur explains in <em>Lisan al-Arab</em> that the core meaning of <em>al-awl</em> (اَلْأَوْل) is returning, reverting, and tracing a matter back to its origin or ultimate outcome. When something <em>ya'ulu</em>, it goes back to a designated state, much like a mountain goat (<em>ayyil</em>) retreating to the safety of the heights. The derivative <em>ta'wil</em> involves navigating a text, event, or symbol back to its primordial significance, primary root, or ultimate destiny. The linguistic nuance thus links superficial appearances directly to their foundational source.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops profound epistemological frameworks for interpreting divine scripture, dreams, and historical outcomes. It guides seekers to look beyond transient phenomena to grasp their ultimate metaphysical destination. A sublime Quranic instance is captured in the divine statement: <em>Wa-lamma yatihim tawiluhu</em> (And when its ultimate interpretation/outcome has not yet reached them), pointing toward the eventual realization of prophetic warnings.</p>"
  },
  {
    "root": "أم/ما",
    "root_meaning_html": "<p>Classical grammarians categorize interrogative and relative particles under compound structures like <em>ma</em> (مَّا), whose primary linguistic function is to inquire about the non-rational reality, essence, or extent of things. The physical and conceptual picture revolves around uncovering obscurity, seeking definition, and drawing forth hidden particulars into clear expression. Lisan al-Arab notes its foundational role in framing human curiosity regarding the nature of the universe and divine actions.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops probing existential questions, negations, and expressions of absolute wonder that awaken human consciousness. It serves as a linguistic mirror reflecting mankind's profound ignorance back toward divine omniscience. A striking Quranic example is found in the query: <em>Ma lam ta'lamu</em> (What you did not know) or interrogative wonderments like <em>Ma al-tariq</em>, piercing through human heedlessness with divine majesty.</p>"
  },
  {
    "root": "أم/ماذا",
    "root_meaning_html": "<p>In classical Arabic lexicography, compound interrogatives such as <em>madha</em> (مَاذَا) merge the particle of inquiry (مَا) with the demonstrative element (ذَا), creating an intensified demand for specification. The foundational concept is to bridge the unknown with the manifest, prompting an immediate accounting of an action, substance, or state. The linguistic nuance moves beyond simple questioning into an assertive challenge directed at the listener's awareness and moral responsibility.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops sharp rhetorical confrontations that compel individuals to evaluate their material output and spiritual readiness. It strips away pretense by demanding precise articulation of belief and action. An exquisite Quranic instance occurs when the disbelievers or seekers are challenged: <em>Wa-yas-alunaka madha yunfiqona qul al-afwa</em> (And they ask you what they should spend. Say: 'The excess...'), providing immediate, practical divine wisdom.</p>"
  },
  {
    "root": "أم/مَن",
    "root_meaning_html": "<p>Lexicographical traditions treat <em>man</em> (مَن) as the foundational relative and interrogative pronoun specifically allotted to rational beings (<em>li-man ya'qilu</em>). The core semantic picture centers upon personality, agency, and moral identity, inquiring directly into the 'who' behind an action or existence. Unlike inanimate inquiries, <em>man</em> immediately invokes consciousness, free will, and accountability, establishing a direct bridge between the questioner and a conscious subject.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops profound theological dialogues concerning human responsibility, divine authority, and existential status. It continually confronts mankind with the reality of moral agency under God. A brilliant Quranic example shines in the verse: <em>Man dha alladhi yuqridu Allaha qardan hasanan</em> (Who is it that would loan Allah a goodly loan?), rousing the human conscience through deeply personal address.</p>"
  },
  {
    "root": "أنّ/ما",
    "root_meaning_html": "<p>In classical Arabic syntax, the fusion of the particle <em>anna</em> with the relative or indefinite <em>ma</em> creates complex subordinating structures that govern modality, emphasis, and temporal clauses. The foundational linguistic gesture involves binding distinct propositional elements into a unified semantic block, anchoring abstract conditions to concrete occurrences. It reflects the intricate architecture of human thought as it transitions from theoretical possibility to enacted reality.</p>",
    "quranic_usage_html": "<p>From this semantic core, the Quranic lexicon richly develops nuanced conditional clauses and emphatic statements that structure narrative flow and legal parameters. It tightly knits divine decrees to temporal realities with flawless precision. A compelling Quranic reflection of this particle combination's structural utility is found throughout verses governing human obligations, seamlessly integrating circumstantial conditions with absolute moral imperatives.</p>"
  }
];
const file = 'database/lexicon/data/comprehensive_root_summaries.json';
let data = JSON.parse(fs.readFileSync(file, 'utf8'));
newData.forEach(item => { data[item.root] = { root_meaning_html: item.root_meaning_html, quranic_usage_html: item.quranic_usage_html }; });
fs.writeFileSync(file, JSON.stringify(data, null, 2));
console.log('Saved 10 extra roots. Total:', Object.keys(data).length);
